CREATE TABLE TAREFA (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TITULO NVARCHAR(32) NOT NULL,
    DESCRICAO NVARCHAR(MAX),
    PRIORIDADE INT NOT NULL CHECK (PRIORIDADE IN (1,2,3,4,5)),
    STATUS CHAR(1) NOT NULL CHECK (STATUS IN ('A', 'C', 'E', 'P','X')),
    DATA_INSERT DATETIME NOT NULL,
    DATA_CONCLUSAO DATETIME
);
/*
STATUS
A - Aberta
C - Concluída
E - Em andamento, iniciada
P - Pendente
X - Cancelada
*/
